port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: :9090
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:5450
  default-nameserver:
    - 202.96.134.133
    - 202.96.128.166
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://1.1.1.1/dns-query
    - tls://dns.adguard.com:853
proxies:
  - {name: c3s1, server: url, port: 5038, type: ss, cipher: aes-256-gcm, password: password}
  - {name: c3s2, server: url, port: 5038, type: ss, cipher: aes-256-gcm, password: password}
  - {name: c3s3, server: url, port: 5038, type: vmess, uuid: 1, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false}
  - {name: c3s4, server: url, port: 5038, type: vmess, uuid: 1, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false}
  - {name: c3s5, server: url, port: 5038, type: vmess, uuid: , alterId: 0, cipher: auto, tls: false, skip-cert-verify: false}
  - {name: c3s801, server: url, port: 5038, type: vmess, uuid: , alterId: 0, cipher: auto, tls: false, skip-cert-verify: false}
proxy-groups:
  - { name: "auto", type: url-test, proxies: ["c3s1", "c3s2", "c3s3","c3s801"], url: "http://www.gstatic.com/generate_204", interval: 300 }
  - {name: "Global",type: select,proxies: ["auto"]}
rules:
  - DOMAIN-KEYWORD,github,Global
  - DOMAIN-KEYWORD,dropbox,Global
  - DOMAIN-KEYWORD, epochtimes,Global

  # instagram and Facebook
  - DOMAIN-KEYWORD, Facebook,Global
  - DOMAIN-KEYWORD, instagram,Global
  - DOMAIN-SUFFIX, fbcdn.net,Global
  - DOMAIN-SUFFIX, fbsbx.com,Global

  # wikipedia
  - DOMAIN-SUFFIX, wikipedia.org,Global
  - DOMAIN-SUFFIX, w.wiki,Global
  - DOMAIN-SUFFIX, wikinews.org,Global
  - DOMAIN-SUFFIX, wiktionary.org,Global
  # wikipedia Image
  - DOMAIN-SUFFIX, wikimedia.org,Global
  - DOMAIN, media.xyzcdn.net,Global

  #copilot
  - DOMAIN-SUFFIX, copilot.microsoft.com,Global
  - DOMAIN-KEYWORD, chatgpt,Global
  - DOMAIN-SUFFIX, openai.com,Global

  # X
  - DOMAIN-SUFFIX, x.com,Global
  - DOMAIN-KEYWORD, twitter,Global
  - DOMAIN-SUFFIX, t.co,Global
  - DOMAIN-SUFFIX, twimg.com,Global

  #discord
  - DOMAIN-KEYWORD, discord,Global
  - DOMAIN-KEYWORD, discordapp,Global

  #perplexity
  - DOMAIN-SUFFIX, perplexity.ai,Global

  # 
  - DOMAIN-KEYWORD, duckduckgo,Global
  - DOMAIN-SUFFIX, scmp.com,Global
  - DOMAIN-SUFFIX, acast.com,Global
  - DOMAIN-SUFFIX, cms-twdigitalassets.com,Global
  - DOMAIN-SUFFIX, axios.com,Global
  - DOMAIN-SUFFIX, blogspot.com,Global
  - DOMAIN-SUFFIX, econ.st,Global
  - DOMAIN-SUFFIX, economist.com,Global
  - DOMAIN-SUFFIX, pixnet.net,Global

  # Apple Podcast
  - DOMAIN-SUFFIX, podcasts.apple.com,Global
  - DOMAIN-SUFFIX, anchor.fm,Global
  - DOMAIN-SUFFIX, podbean.com,Global
  - DOMAIN-SUFFIX, blubrry.com,Global
  - DOMAIN-SUFFIX, buzzsprout.com,Global
  - DOMAIN-SUFFIX, soundon.fm,Global
  - DOMAIN-SUFFIX, pdst.fm,Global

  # FT
  - DOMAIN-SUFFIX, ft.com,Global
  - DOMAIN-SUFFIX, ftchinese.com,Global
  # FT Image
  - DOMAIN-SUFFIX, ftimg.net,Global

  # NYT
  - DOMAIN-SUFFIX, nytimes.com,Global
  - DOMAIN-SUFFIX, nyti.ms,Global
  # NYT
  - DOMAIN-SUFFIX, nyt.com,Global

  # rfa
  - DOMAIN-SUFFIX, rfa.org,Global

  # DW
  - DOMAIN-SUFFIX, dw.com,Global
  - DOMAIN-SUFFIX, dwcdn.net,Global

  # RFi
  - DOMAIN-SUFFIX, rfi.fr,Global
  - DOMAIN-SUFFIX, rfi.my,Global

  #rss
  - DOMAIN-SUFFIX, feedly.com,Global
  - DOMAIN-SUFFIX, rsshub.app,Global

  #ABC
  - DOMAIN-SUFFIX, ab.co,Global
  - DOMAIN-SUFFIX, abc.net.au,Global
  - DOMAIN-SUFFIX, abc-cdn.net.au,Global

  # WSJ
  - DOMAIN-SUFFIX, wsj.com,Global
  - DOMAIN-SUFFIX, wsj.net,Global

  # Thenitium
  - DOMAIN-SUFFIX, theinitium.com,Global

  # TW
  - DOMAIN-SUFFIX, cna.com.tw,Global

  # Pinterest
  - DOMAIN-SUFFIX, Pinterest.com,Global
  - DOMAIN-SUFFIX, pinimg.com,Global

  #
  - DOMAIN-SUFFIX, bit.ly,Global
  - DOMAIN-SUFFIX, cloudfront.net,Global

  # VOA
  - DOMAIN-SUFFIX, voachinese.com,Global
  - DOMAIN-SUFFIX, weserv.nl,Global
  - DOMAIN-SUFFIX,disqus.com,Global
  # VOA
  - DOMAIN-SUFFIX, voanews.com,Global

  # Nikkei
  - DOMAIN-SUFFIX, nikkei.com,Global

  # BBC
  - DOMAIN-SUFFIX, bbc.com,Global
  - DOMAIN-SUFFIX, bbc.in,Global
  - DOMAIN-SUFFIX, bbc.co.uk,Global
  - DOMAIN-SUFFIX, bbci.co.uk,Global

  # Bloomberg
  - DOMAIN-SUFFIX, bloomberg.com,Global
  - DOMAIN-SUFFIX, fast.com,Global

  # Medium
  - DOMAIN-SUFFIX, medium.com,Global

  #Reddit
  - DOMAIN-KEYWORD, reddit,Global
  - DOMAIN-SUFFIX, redd.it,Global

  # Yahoo
  - DOMAIN-KEYWORD, Yahoo,Global
  - DOMAIN-SUFFIX, xhamster.com,Global
  - DOMAIN-SUFFIX, yimg.com,Global

  - DOMAIN-SUFFIX, i-scmp.com,Global

  # Amazon
  - DOMAIN-SUFFIX, amazon.co.jp,Global

  # other
  - DOMAIN-SUFFIX, flickr.com,Global
  - DOMAIN-SUFFIX, matters.news,Global
  - DOMAIN-SUFFIX, quora.com,Global
  - DOMAIN-SUFFIX, pincong.rocks,Global
  - DOMAIN-SUFFIX, v2ex.com,Global
  - DOMAIN-SUFFIX, washingtonpProxyt.com,Global
  - DOMAIN-SUFFIX, nypost.com,Global

  # Reuter
  - DOMAIN-SUFFIX, reuters.com,Global
  - DOMAIN-SUFFIX, reut.rs,Global

  #Foxnews
  - DOMAIN-SUFFIX, fxn.ws,Global
  - DOMAIN-SUFFIX, foxnews.com,Global
  - DOMAIN-SUFFIX, foxbusiness.com,Global

  - DOMAIN-SUFFIX, zerohedge.com,Global
  - DOMAIN-SUFFIX, tru.am,Global
  - DOMAIN-KEYWORD, dianomi,Global
  - DOMAIN-SUFFIX, chinadigitaltimes.net,Global
  - DOMAIN-SUFFIX, greatfire.org,Global
  - DOMAIN-SUFFIX, creaders.net,Global
  - DOMAIN, ocsp.pki.goog,Global

  - DOMAIN-SUFFIX, torproject.org,Global
  - DOMAIN-SUFFIX, chosun.com,Global

  # Freeweibo\Freeweichat\freezhihu
  - DOMAIN-KEYWORD, free,Global
  - DOMAIN-SUFFIX, gstatic.com,Global
  - DOMAIN-SUFFIX, bumingbai.net,Global
  - DOMAIN-SUFFIX, yibaochina.com,Global
  - DOMAIN-SUFFIX, ltn.com.tw,Global
  - DOMAIN-SUFFIX, thetimes.co.uk,Global
  - DOMAIN-SUFFIX, mac.gov.tw,Global
  - DOMAIN-SUFFIX, secretchina.com,Global
  - DOMAIN-SUFFIX, matters.town,Global

  # Google and Youtube
  - DOMAIN-KEYWORD, Google,Global
  - DOMAIN-KEYWORD, Gmail,Global
  - DOMAIN-KEYWORD, youtube,Global
  - DOMAIN-SUFFIX, goo.gl,Global
  - DOMAIN-SUFFIX, Youtu.be,Global
  # Google and Youtube movie and image
  - DOMAIN-SUFFIX, ytimg.com,Global
  - DOMAIN-SUFFIX, ggpht.com,Global

  #Adobe Firefly
  - DOMAIN-SUFFIX, adobe.io,Global
  - DOMAIN, firefly.adobe.com,Global
  - DOMAIN, odin.adobe.com,Global
  - DOMAIN, hbrt.adobe.com,Global

  # Spotify
  - DOMAIN-SUFFIX, pscdn.co,Global
  - DOMAIN-SUFFIX, scdn.co,Global
  - DOMAIN-SUFFIX, spoti.fi,Global
  - DOMAIN-SUFFIX, spotilocal.com,Global
  - DOMAIN-KEYWORD, spotify,Global

  - DOMAIN-SUFFIX, hallowlib.org,Global
  - DOMAIN-KEYWORD, justmysocks,Global
  #telegram
  - DOMAIN-KEYWORD,telegram,Global
  - DOMAIN-SUFFIX,t.me,Global
  - DOMAIN-SUFFIX,telegra.ph,Global
  - DOMAIN-SUFFIX, pornhub.com,Global
  # CN and other
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT
